---

deploy_mirror: false

src_registry: registry.access.redhat.com
dest_registry: localhost:5555

ose_minor_tag: v3.6.173.0.21
ose_major_tag: v3.6

ose_core_images:
  - openshift3/ose:latest
  - openshift3/ose:{{ ose_minor_tag }}
  - openshift3/ose:{{ ose_major_tag }}
  - openshift3/node:latest
  - openshift3/node:{{ ose_minor_tag }}
  - openshift3/node:{{ ose_major_tag }}
  - openshift3/openvswitch:latest
  - openshift3/openvswitch:{{ ose_minor_tag }}
  - openshift3/openvswitch:{{ ose_major_tag }}
  - rhel7/etcd:latest

ose_infra_images:
  - openshift3/ose-haproxy-router:{{ ose_minor_tag }}
  - openshift3/ose-deployer:{{ ose_minor_tag }}
  - openshift3/ose-recycler:{{ ose_minor_tag }}
  - openshift3/ose-sti-builder:{{ ose_minor_tag }}
  - openshift3/ose-docker-builder:{{ ose_minor_tag }}
  - openshift3/ose-pod:{{ ose_minor_tag }}
  - openshift3/ose-docker-registry:{{ ose_minor_tag }}
  - openshift3/logging-deployer:{{ ose_major_tag }}
  - openshift3/logging-elasticsearch:{{ ose_major_tag }}
  - openshift3/logging-kibana:{{ ose_major_tag }}
  - openshift3/logging-fluentd:{{ ose_major_tag }}
  - openshift3/logging-curator:{{ ose_major_tag }}
  - openshift3/logging-auth-proxy:{{ ose_major_tag }}
  - openshift3/metrics-deployer:{{ ose_major_tag }}
  - openshift3/metrics-hawkular-metrics:{{ ose_major_tag }}
  - openshift3/metrics-cassandra:{{ ose_major_tag }}
  - openshift3/metrics-heapster:{{ ose_major_tag }}
  - openshift3/registry-console:{{ ose_major_tag }}

cns_core_images:
  - rhgs3/rhgs-volmanager-rhel7:3.2.0-11
  - rhgs3/rhgs-server-rhel7:3.2.0-7

...
