---

deploy_mirror: false

registry_port: 5555

src_registry: registry.access.redhat.com
dest_registry: "localhost:{{ registry_port }}"

ose_minor_tag: v3.6.173.0.21
ose_major_tag: v3.6

rhgs_server_tag: 3.2.0-11
rhgs_volmanager_tag: 3.2.0-7

ose_core_images:
  - openshift3/ose
  - openshift3/node
  - openshift3/openvswitch

ose_infra_images:
  - openshift3/ose-haproxy-router
  - openshift3/ose-deployer
  #- openshift3/ose-recycler
  - openshift3/ose-sti-builder
  - openshift3/ose-docker-builder
  - openshift3/ose-pod
  - openshift3/ose-docker-registry
  - openshift3/logging-deployer
  - openshift3/logging-kibana
  - openshift3/logging-fluentd
  - openshift3/logging-curator
  - openshift3/logging-auth-proxy
  - openshift3/metrics-deployer
  - openshift3/metrics-hawkular-metrics
  - openshift3/metrics-cassandra
  - openshift3/metrics-heapster
  - openshift3/registry-console

ose_s2i_images:
  - openshift3/logging-elasticsearch:{{ ose_major_tag }}
  - rhscl/ruby-23-rhel7:latest
  - rhscl/postgresql-95-rhel7:latest

rhel_core_images:
  - rhel7/etcd:latest

cns_core_images:
  - rhgs3/rhgs-volmanager-rhel7:{{ rhgs_server_tag }}
  - rhgs3/rhgs-server-rhel7:{{ rhgs_volmanager_tag }}

...
